### ISSUE TITLE
BIRT report engine crashes for repot that works in Eclipse Report Designer

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-reporting#39]
I have two versions of the same report, both working in my report designer 
The more complex one seems to trigger an exception on our ReportServer.

From /var/log/tomcat7/catalina.out:

Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
at java.util.ArrayList.rangeCheck(ArrayList.java:635)
at java.util.ArrayList.get(ArrayList.java:411)
at org.eclipse.birt.report.model.elements.GridItem.getCellPositionInColumn(GridItem.java:393)
at org.eclipse.birt.report.model.elements.GridItem.cacheValues(GridItem.java:267)

I have logged a suppport request with Datenwerke:
https://support.datenwerke.net/support/tickets/291

**Comment by stellanl** [comment]
Datenwerke replied that this is probably this bug:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=446077

and supplied a patched WEB-INF/lib/org.eclipse.birt.runtime-4.4.1.jar

**Comment by stellanl** [comment]
I installed the patch on reports.test.akvo-ops.org and it works.
